### ISSUE TITLE
QueryRunner#run does not support paged results

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-core#121]
It is not possible to retrieve a specific page of results from the Query API due to the way that QueryRunner#run calls get_all_results.

It would be good to add support for the :page option, to  limit search results. This is useful for large dataset types, such as 'task'. The API we are giving people at the moment encourages getting all results,
which can be time consuming.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
