### ISSUE TITLE
Config Validator does not give context as to where a failure occurs (line number, or breadcrumb trail)

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-core#122]
At present error messages from the configuration validator are along the lines of:

F, [2014-03-05T15:48:41.112850 #35075] FATAL -- : http: is not a hash
Supplied configuration does not match supplied schema

This does not give the user any information as to where the problematic entry occurs, such as a breadcrumb trail or a line number.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
