### ISSUE TITLE
Specify and populate config defaults using schema

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-core#123]
As a user,
I would like config defaults to be documented in schemas,
So that I don't have to look through code logic to determine which key/values can be omitted.

This is mostly prompted by looking at vCloud Edge Gateway. There is lots of useful information in the [README](https://github.com/gds-operations/vcloud-edge_gateway#configure-edge-gateway-services) about defaults.

These are otherwise buried within `Vcloud::EdgeGateway::ConfigurationGenerator::*`, e.g. https://github.com/alphagov/vcloud-edge_gateway/blob/v0.5.0/lib/vcloud/edge_gateway/configuration_generator/firewall_service.rb

It feels like the schema *might* be the right place to centralise this information. Albeit changing the behaviour of Core::ConfigValidator quite drastically. Kwalify has something similar: http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html#schema-rules

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
