### ISSUE TITLE
It would be good to have validation of the form "optional, but if this then that"

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-core#124]
The 'original_port' setting for NAT rules is [optional](https://github.com/gds-operations/vcloud-edge_gateway/blob/e0c3685fc51b8b52de4871c7d314b86fe640c212/lib/vcloud/edge_gateway/schema/nat_service.rb#L14).

However, if you set a `translated_port` you also need to set an `original_port`. Our validation doesn't cover this, so you then get an unhelpful error from the vShield Edge if you accidentally forget one:

```
0:04  E, [2014-05-15T15:50:54.041789 #40884] ERROR -- : Could not update EdgeGateway d627d7c2-8e48-438e-9f77-98a7fb164ee9 : status: error, error: {:minorErrorCode=>"NETWORK_INTERNAL_SERVER", :message=>"Unable to perform this action. Contact your cloud administrator.", :majorErrorCode=>"500"}
E, [2014-05-15T15:50:54.041944 #40884] ERROR -- : status: error, error: {:minorErrorCode=>"NETWORK_INTERNAL_SERVER", :message=>"Unable to perform this action. Contact your cloud administrator.", :majorErrorCode=>"500"}
```

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this pull request. Thank you for your interest and involvement in this project.
