### ISSUE TITLE
vCloud Core creates new session many times in a single run contributing to it running slowly

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-core#134]
We call `::Fog::Compute::VcloudDirector.new` in VcloudSession many times.

This isn't a problem with small orgs but as we get bigger, it becomes a problem.

The slow down is because fog verifies the session is legit, which takes a few 100ms. This can add up quickly.

As an example, each of the resources here calls `Vcloud::Core::Fog::ServiceInterface.new` twice, once to [get the href](https://github.com/gds-operations/vcloud-core/blob/master/lib/vcloud/core/edge_gateway.rb#L49) and once to [get the name](https://github.com/gds-operations/vcloud-core/blob/master/lib/vcloud/core/edge_gateway.rb#L53).

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
