### ISSUE TITLE
Check that a disk is fully detached before destroying

### ISSUE THREAD

**Issue by mikepea** [gds-operations/vcloud-core#149]
Raised initially as a concern with the code in #141, but now also extends to the integration tests in vcloud-launcher: https://github.com/gds-operations/vcloud-launcher/blob/v0.7.0/spec/integration/launcher/launch_spec.rb#L184

The underlying 'DELETE /disk' API call (exposed via https://github.com/gds-operations/vcloud-core/blob/master/lib/vcloud/core/fog/service_interface.rb#L139 ) does actually error if a disk is still attached, and the call fails accordingly.

However, there is a corner case where the IndependentDisk#attached_vms call reports that no VMs are attached to the disk after a vApp deletion, but the delete_disk call will fail with the 'disk is still attached' message.

As yet, I know of no way to ascertain that the disk is in this state - the only way is to delay at least 15s between a vApp delete and IndependentDisk#destroy operation.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
