### ISSUE TITLE
Change ownership details in Gemspec?

### ISSUE THREAD

**Issue by ajlanghorn** [gds-operations/vcloud-core#157]
Currently, the Gemspec lists @annashipman as the owner of the vcloud-core Gem (it may be that she's also listed as the owner on other Gems, too, but I've not checked). These Gems are now in the `gds-operations` organization, and pull requests are primarily (at the moment) reviewed and merged by the Infrastructure and Tools team.

To that end, do we want to amend the Gemspec to point the owner and contact email address to a mailing list?

**Comment by annashipman** [comment]
Good idea.

**Comment by ajlanghorn** [comment]
Great; thanks @annashipman. Will raise in a PR this morning.

**Comment by annashipman** [comment]
Oops, sent that before I'd finished. Have a chat with @alext, he's looked into this. Also, there's a story somewhere in our backlog about this, I think. And you know of course that there is a vcloud-tools mailing list.

**Comment by ajlanghorn** [comment]
Yep, @rjw1 mentioned that to me. I'll go find @alext to ask and see if I can dig up that story.
