### ISSUE TITLE
vcloud-logout gives error: ArgumentError: Missing required arguments: vcloud_director_password

### ISSUE THREAD

**Issue by edmundcraske** [gds-operations/vcloud-core#172]
If I run vcloud-logout with a valid FOG_VCLOUD_TOKEN in my shell env, it spits out the error:
'ArgumentError: Missing required arguments: vcloud_director_password'

At a guess this may be due to an upstream change in fog?

Versions I'm using:
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

vcloud-core (1.0.2)
fog (1.31.0)
fog-core (1.31.1)

**Comment by edmundcraske** [comment]
Actually I needed to read the usage instructions more closely - my ~/.fog file needed to have "vcloud_director_password: ''" in it, rather than not having it at all.

I'm not sure why this is needed when it's blank anyway - the error could be more useful!

**Comment by annashipman** [comment]
This is a [requirement in fog](https://github.com/fog/fog/blob/master/lib/fog/vcloud_director/compute.rb#L46) and the error message comes from there as well. It would be helpful if it wasn't required if you had a token!
