### ISSUE TITLE
Username formatting when it is an email address

### ISSUE THREAD

**Issue by asciifaceman** [gds-operations/vcloud-core#180]
I am receiving 500 errors on vcloud-login (unauthorized.header.malformed) and wondered if it might have been my credential set. My auth username is an email address, so user@org would leave two @'s in the variable. Am I going about this wrong? I haven't been able to find if there is an internal representation of my username, or if this is just like everything else vCloud and just doesn't work for me.

**Comment by mattbostock** [comment]
Hi @asciifaceman,

There's a [known issue](https://github.com/gds-operations/vcloud-tools/issues/217) with `vcloud-login` currently. Are you able to log in if you remove the `eval` wrapper and just run `vcloud-login` with your `FOG_CREDENTIAL` set, e.g.:

```
FOG_CREDENTIAL=xyz vcloud-login
```

**Comment by asciifaceman** [comment]
Unfortunately no, I have messed around a bit with the credentials. I am
wondering if I am using the wrong API endpoint, as it isn't *super clear*
what I am supposed to use. Presently I have :vcair_api_host set to
us-california-1-3.vchs.vmware.com

On Wed, Sep 30, 2015 at 3:37 AM, Matt Bostock <notifications@github.com>
wrote:

> Hi @asciifaceman <https://github.com/asciifaceman>,
>
> There's a known issue
> <https://github.com/gds-operations/vcloud-tools/issues/217> with
> vcloud-login currently. Are you able to log in if you remove the eval
> wrapper and just run vcloud-login with your FOG_CREDENTIAL set, e.g.:
>
> FOG_CREDENTIAL=xyz vcloud-login
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gds-operations/vcloud-core/issues/180#issuecomment-144350516>
> .
>



-- 
Charles P. Corbett

**Comment by asciifaceman** [comment]
For clarity: I was receiving the \r error at first (as is obvious in our email chain), but I had figured out that not using eval gets rid of that and then was hit with the 500 errors.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
