### ISSUE TITLE
CatalogueItem query should be Org_Name scoped

### ISSUE THREAD

**Issue by tlawrence** [gds-operations/vcloud-core#183]
Multiple Catalog items may be returned if user owns templates with same template & catalogue name in multiple orgs:

e.g

```
org1 =>
  catalogue=>
    name => ubuntu
    template => ubuntu_12_04
    owner => username
org2 =>
  catalogue=>
    name => ubuntu
    template => ubuntu_12_04
    owner => username
```

We think VMware may have changed the behavior of this query (we are checking) in a recent release.

To fix this changes need to be made to:
lib/vcloud/core/vapp_template.rb

```
query_results = q.run('vAppTemplate', :filter => "name==#{name};catalogName==#{catalog_name}")
```

should become

```
org_name = #GET FROM SERVICE SOMEHOW...

query_results = q.run('vAppTemplate', :filter => "name==#{name};catalogName==#{catalog_name};org==#{org_name}")
```

I dont have a working dev environment setup for this else I'd submit a PR. 
If someone could point out an easy way to get the org_name form the service connection within the vapp_template class then I'll add it. 

Tim

**Comment by tlawrence** [comment]
looked at this again earlier. I think the best thing would be to inject an org filter into the query_runner.run method. Most other methods in vCloud Tools (and Fog..) assume a tight scoping to a vCloud Organisation. Running queries without this filter can result in unexpected responses (as has happened in this instance).

Can anyone acknowledge this issue and provide comment?

Tim

**Comment by rjw1** [comment]
Thanks for the report Tim. 
We would happily look at a pull request to fix this.

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this pull request. Thank you for your interest and involvement in this project.
