### ISSUE TITLE
Deployment using vcloud-launcher

### ISSUE THREAD

**Issue by smford** [gds-operations/vcloud-core#195]
When deploying using vcloud launcher we receive this error back:

```
# bundle exec vcloud-launch path/to/servers.yaml
I, [2017-06-30T13:23:55.273344 #26292]  INFO -- : Provisioning vApp dns-3.tools.internal.
I, [2017-06-30T13:24:00.009629 #26292]  INFO -- : Instantiating new vApp dns-3.tools.internal in vDC 'idap_development (IL2-DEVTEST-STANDARD)'
undefined method `get_networks' for Vcloud::Core::Vapp:Class
```

Gemfile:
```
ruby '2.3.1'

source 'https://rubygems.org'

gem 'vcloud-edge_gateway', '2.1.0'
gem 'vcloud-launcher',     '2.1.0'
gem 'vcloud-net_launcher', '2.2.2'
gem 'vcloud-walker',       '5.1.0'
...
```

**Comment by surminus** [comment]
Hi Steve,

Thanks for raising this. It looks like it's related to a [recent change I made](https://github.com/gds-operations/vcloud-core/commit/111d52a43a4deb45fec2b492475bd445b5aac623).

I will look into resolving this. 

Thanks,
Laura

**Comment by surminus** [comment]
Hi Steve,

I've just merged a PR which should hopefully fix this issue: https://github.com/gds-operations/vcloud-core/pull/196

This will release a newer version of vcloud-core (2.1.1). 

Laura

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this pull request. Thank you for your interest and involvement in this project.
